fix(docsearch): suppress error for status code 3

diff --git a/.github/workflows/docsearch.yml b/.github/workflows/docsearch.yml
--- a/.github/workflows/docsearch.yml
+++ b/.github/workflows/docsearch.yml
@@ -1,4 +1,4 @@
-name: Run algolia dockersearch
+name: Run algolia docsearch
 
 on:
   push:
@@ -10,11 +10,25 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
-    - run: |
+
+    - name: Setup environment
+      run: |
         echo "APPLICATION_ID=$APPLICATION_ID" >> .env
         echo "API_KEY=$API_KEY" >> .env
         chmod +x ./bin/crawl.sh
-        ./bin/crawl.sh
       env:
         APPLICATION_ID: ${{ secrets.ALGOLIA_DOCSEARCH_APP_ID }}
         API_KEY: ${{ secrets.ALGOLIA_DOCSEARCH_API_KEY }}
+
+    - name: Run docsearch
+      run: |
+        ./bin/crawl.sh
+        if [ $? -eq 3 ]; then
+          echo "Docsearch succeeded, but docs weren't updated"
+          exit 0
+        fi
+
+        if [ $? -ne 0 ]; then
+          echo "Failed to run docsearch"
+          exit 1
+        fi
